version: "3.9"

services:
  db:
    image: postgres:16
    container_name: dice_postgres
    environment:
      POSTGRES_USER: dice_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dice_db
    ports:
      - "5432:5432"
    volumes:
      - dice_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  dice_db_data:
